### ISSUE TITLE
Failing config check

### ISSUE THREAD

**Issue by louwersj** [Oracle-CEG-CN/egeria-connector-oci#1]
https://github.com/Oracle-CEG-CN/egeria-connector-oci/blob/f83991015a8e63ba61a2c4e2312d6239fa4d488c/data_catalog_event_handler/func.py#L27

What would happen if the check fails and the OCI config is not valid. Guess this needs some error catching(?)

**Comment by StefanHoening** [comment]
I have restructured the code and added exception handling (logging).
